### ISSUE TITLE
Network Rewrite Tracking

### ISSUE THREAD

**Issue by PoisonNinja** [PoisonNinja/ToyOS#3]
Networking layer is currently pretty messy. We should rewrite it.

- [ ] Ethernet frames
- [ ] IPv4 headers
- [ ] UDP packets
- [ ] UDP packet checksums
- [ ] TCP packets
- [ ] ARP
- [ ] DHCP packet construction
- [ ] DHCP packet interpretation (options)
- [ ] DNS
- [ ] Request generation
- [ ] Response parsing
- [ ] IRC
- [ ] Telnet
- [ ] Userspace interface

**Comment by Saruta** [comment]
Do you want to do a separate module for each item?

**Comment by PoisonNinja** [comment]
Edited to OP. The ones under modules should be in seperate modules, and everything under userspace can be however you want.
